### ISSUE TITLE
MCP Crate Sources Config

### ISSUE THREAD

**Issue by mrchantey** [mrchantey/beet#48]
We need to be able to configure and share the source info for each crate for rag indexing. Now that the `KnownSources` can be serialized and passed in we can work on a config format.

Something like this might work with the current `ContentSource` type.

```toml
# beet.toml


[crate-sources]

[[include]]
path = "https://github.com/mrchantey/beet/crate-sources/bevy-and-friends.toml"

[[include]]
path = "./my-other-sources.toml"

[[source]]
crate-name = "bevy"
crate-version = "0.16.0"
content-type = "guides"
git-url = "https://github.com/bevyengine/bevy-website"
git-commit = "abc123"
filter = "*/*.md"

[[source]]
crate-name = "bevy"
crate-version = "0.16.0"
content-type = "examples"
git-url = "https://github.com/bevyengine/bevy"
git-commit = "abc123"
git-branch = "dev"
filter = "**/examples/**/*.rs"
split-text.chunk-range.min=1500
split-text.chunk-range.max=3000
```

Also I think this change could include making the `ContentType` just a `String`, and including content type descriptions in the config instead of hardcoded [like we're currently doing here](https://github.com/mrchantey/beet/blob/12d48e0baf8baf21b5e6cfdc5060c69dea3d4382/crates/beet_mcp/src/crate_rag/content_type.rs#L12).
